### ISSUE TITLE
tw.lua:69 Unable to localize

### ISSUE THREAD

**Issue by Roland-1223** [NORPG/AllTheThings#1]
**Game Flavor (please complete the following information):**
 - Flavor: [e.g. Dragonflight, Cataclysm, Classic Era]
Cataclysm
**Describe the bug**

Unable to localize

23x AllTheThings/locales/tw.lua:69: attempt to index field '?' (a nil value)
[string "@AllTheThings/locales/tw.lua"]:69: in main chunk

Locals:
app =

{
AlwaysShowUpdateWithoutReturn = defined @AllTheThings/src/base.lua:35
indexOf = defined @AllTheThings/lib/Table.lua:37
SetScript = defined @AllTheThings/lib/EventRegistration.lua:47
FunctionRunner =
{
}
GetRelativeRawWithField = defined @AllTheThings/src/base.lua:166
DefaultColors =
{
}
Sort = defined @AllTheThings/lib/Sort.lua:384
GetDeepestRelativeValue = defined @AllTheThings/src/base.lua:140
RaceID = 8
PrintDebug = defined @AllTheThings/lib/Print.lua:19
CloneReference = defined @AllTheThings/src/base.lua:88
HandleEvent = defined @AllTheThings/src/Events.lua:132
ShowPopupDialog = defined @AllTheThings/src/base.lua:374
ReturnFalse = defined @AllTheThings/src/base.lua:37
EmptyTable =
{
}
RaceIndex = 8
DESCRIPTION_SEPARATOR = "`"
Class = "MAGE"
asset = defined @AllTheThings/src/base.lua:31
SortGroup = defined @AllTheThings/lib/Sort.lua:388
GetBestMapForGroup = defined @AllTheThings/src/base.lua:110
RemoveEventHandler = defined @AllTheThings/src/Events.lua:32
SortDefaults =
{
}
CallbackHandlers =
{
}
StartCoroutine = defined @AllTheThings/lib/Runner.lua:158
RegisterEvent = defined @AllTheThings/lib/EventRegistration.lua:31
GameBuildVersion = 40400
RefreshCollections = defined @AllTheThings/lib/Refresh.lua:333
events =
{
}
Runners =
{
}
frame = Frame {
}
AlwaysShowUpdate = defined @AllTheThings/src/base.lua:34
RegisterFuncEvent = defined @AllTheThings/lib/EventRegistration.lua:34
print = defined @AllTheThings/lib/Print.lua:7
L =
{
}
ClearSounds = defined @AllTheThings/lib/Audio.lua:180
AddSound = defined @AllTheThings/lib/Audio.lua:159
AddEventHandler = defined @AllTheThings/src/Events.lua:19
IsClassic = true
AssignFieldValue = defined @AllTheThings/src/base.lua:62
round = defined @AllTheThings/src/base.lua:105
CallbackEvent = defined @AllTheThings/src/Events.lua:177
ClassIndex = 8
report = defined @AllTheThings/lib/Print.lua:10
WOWAPI =
{
}
Audio =
{
}
IsRetail = false
ReturnTrue = defined @AllTheThings/src/base.lua:36
ShowPopupDialogToReport = defined @AllTheThings/src/base.lua:531
ArrayAppend = defined @AllTheThings/lib/Table.lua:61
CreateRunner = defined @AllTheThings/lib/Runner.lua:312
ShowPopupDialogWithMultiLineEditBox = defined @AllTheThings/src/base.lua:427
ShowPopupDialogWithEditBox = defined @AllTheThings/src/base.lua:394
Colors =
{
}
Faction = "Horde"
GetRelativeValue = defined @AllTheThings/src/base.lua:152
StartATTCoroutine = defined @AllTheThings/src/base.lua:349
SetCustomColors = defined @AllTheThings/lib/Colors.lua:42
LocalizeGlobalIfAllowed = defined @AllTheThings/src/base.lua:259
LocalizeGlobal = defined @AllTheThings/src/base.lua:247
containsValue = defined @AllTheThings/lib/Table.lua:32
IgnoreDataCaching = defined @AllTheThings/src/base.lua:224
Race = "Troll"
ClassName

**Comment by NORPG** [comment]
Fix in c60c2768861083e99dee1df3b0e72f319770a3b0
Thanks for your report

**Comment by Roland-1223** [comment]
Tested again on 4.0.15, still the same error message

**Comment by NORPG** [comment]
My guess is that the description of the Worldsoul Saga is missing in _classic/locales.lua_, rather than the missing semicolon(;) in _locales/tw.lua_.
However, I don’t have an active subscription, so I can’t test the changes in Classic.

**Comment by NORPG** [comment]
Currently, the Classic version uses the localization file _classic/locales.lua_, while the retail version uses _locales/en.lua_. 
I am in the process of migrating both of these files to _locales/Default Locales.lua_, but the changes are too extensive to complete all at once. 
So far, I have only completed part of the migration.

**Comment by Roland-1223** [comment]
It can be localized normally without any error messages. Thank you for your hard work.
